services:
  node-red:
    build: .
    environment:
      TZ: ${TZ}
      KC_REALM: ${KC_REALM}
      KC_CLIENT_ID: ${KC_CLIENT_ID}
      KC_CLIENT_SECRET: ${KC_CLIENT_SECRET}
      KC_AUTH_URL: ${KC_AUTH_URL}
      KC_CALLBACK_URL: ${KC_CALLBACK_URL}
      KC_ADMIN_ROLE: ${KC_ADMIN_ROLE}
    ports:
      - "${NODERED_PORT}:1880"
    volumes:
      - data:/data

volumes:
  data:
    external: false
