name: ${STACK_NAME}

services:
  node-red:
    build: .
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "${HTTP_PORT}:1880"
    volumes:
      - data:/data

volumes:
  data:
    external: false
