services:
  node-red:
    build: .
    user: root
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "${NODERED_PORT}:1880"
    volumes:
      - data:/data

volumes:
  data:
    external: false
